### PR TITLE
Improve readability

### PR DESCRIPTION
**Pull request by HarshilShah**
Bumps up the font-size and line-height, and limits the width of text areas on larger screens

### CODE REVIEW

**Comment by jessesquires** [comment]
Thanks @HarshilShah! :smile:

With [bootstrap](http://getbootstrap.com/docs/4.0/layout/grid/), the max container width ends up being `945px` which I think is ok. `900` feels a bit too narrow to me. And `17px` for font size feels a bit too big to me, but I do agree that it could be a bit larger — I'll bump that up slightly!

In any case, most modern browsers allow you to increase font size and there's also things like Safari Reader. So I think I'll close this, but thanks for pointing this out! :raised_hands:

**Comment by HarshilShah** [comment]
Hmm, makes sense. Btw, Bootstrap has a higher limit for higher res breakpoints, so on my 15-inch MBP with a higher resolution than default, the max-width I'm seeing is 1170px: 
screen shot 2017-10-30 at 8 10 29 pm

**Comment by jessesquires** [comment]
Ah interesting!

I have the container set to `col-md-10`. 

Maybe we need to specify [`lg` and `xg`](http://getbootstrap.com/docs/4.0/layout/grid/)?

**Comment by HarshilShah** [comment]
Yeah, seems like that's the issue. `col-lg-8` would be the next logical size, but that is only 750px though 🤔

**Pull request closed without merging**
